version: '3.7'

services:
    amazon:
        container_name: amazon
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - 3000:3000
